fix: queries related to badges
thebadge/thebadge-dapp pull request #104
Opened 2023-05-18 21:43 UTC by FedeMadoery

# Description

This PR is the continuation of the #102 where I address all the queries related to Badges

2023-05-23 09:32 UTC, ramabit commented
Considerate using the last version of the UI lib (1.6.1) and use BadgePreview instead of BadgePreviewV2

2023-05-23 11:32 UTC, FedeMadoery commented on src/pagePartials/profile/created/BadgesCreatedSection.tsx
> +      const mintCost = '100000000000000' //badgeModel.mintCost;
Here I made a ticket for this, #107. We will need to create some sort of hook, that fetches the needed data and made the maths

2023-05-23 15:15 UTC, nicosampler commented on src/hooks/subgraph/useBadgeById.tsx
> +    const cleanedBadgeMetadataHash = badge?.uri.replace(/^ipfs?:\/\//, '')
can we move the replace to a function?

2023-05-23 15:16 UTC, nicosampler commented on src/hooks/subgraph/useBadgeById.tsx
> +    const cleanedBadgeMetadataHash = badge?.uri.replace(/^ipfs?:\/\//, '')
perhaps we can handle it automatically on getFromIPFS, si the URL starts with the protocol IPFS, we do the change.

2023-05-23 16:40 UTC, FedeMadoery commented on pages/badge/model/create.tsx
> +            metadata: `ipfs://${badgeModelIPFSUploaded.result?.ipfsHash}`, // TODO: should we use a custom one? or the one for TCR is ok?
Good catch

2023-05-23 16:41 UTC, FedeMadoery commented on src/hooks/subgraph/useBadgeById.tsx
> +    const cleanedBadgeMetadataHash = badge?.uri.replace(/^ipfs?:\/\//, '')
It's actually doing it, I forgot to remove the _replace_

2023-05-24 09:16 UTC, Agupane requested changes

2023-05-24 09:16 UTC, Agupane commented on src/hooks/subgraph/useBadgeKlerosMetadata.tsx
> +export function useBadgeKlerosMetadata(badgeId: string, options?: BadgeModelHooksOptions) {
`"BadgeKleros"` is still a little weird for me as it's not self-explanatory what's exactly, I know that this is subgraph stuff, but can we at least add a comment above the function that explains that this is the "community badge metadata" or something like that?

2023-05-24 09:16 UTC, Agupane commented on src/pagePartials/badge/curate/challenge/ChallengeModal.tsx
> +  if (!badge) {
Same

2023-05-24 10:44 UTC, FedeMadoery commented on pages/badge/model/create.tsx
> +      name, //badgeModelName
I need to do some work around the creation, I can take care of that at that point

2023-05-24 11:16 UTC, FedeMadoery commented on pages/badge/preview/[badgeId].tsx
> +  const badgeById = useBadgeById(badgeId)
The only clean way to address this I having a wrapper for each hook like "_useBadgeById_" or "_useBadgeModel_", since we are using SWR (`useSWR`) to accomplish the suspense behavior, so the returned value is always a promise, with that in mind you never know if the "data" is there or not, you always need to do the validation. With that said, we can move the validation using a wrapper, but I don't like it too much, I prefer to have it in the component and be aware of the exceptional flows that your component or screen would have.

Anyways, I am open to discussing it, maybe I'm missing something

2023-05-24 11:17 UTC, FedeMadoery commented on src/hooks/subgraph/useBadgeKlerosMetadata.tsx
> +export function useBadgeKlerosMetadata(badgeId: string, options?: BadgeModelHooksOptions) {
I will do my best, for me its very clear bc that's the name of the entity (`BadgeKlerosMetadata`) on the SG, but you have a point haha

2023-05-24 19:35 UTC, merged