WIP: Use expiration overlay and claim badge
thebadge/thebadge-dapp pull request #129
Opened 2023-07-06 16:00 UTC by ramabit

# Description

- Adding usage of expiration overlay
- Add claim badge button if review is completed (pending ready 100%)
- Fix loading badge lists

2023-07-06 17:58 UTC, FedeMadoery commented on src/constants/helpers.ts
> +  date.setMonth(date.getMonth() + 3)
How does this work if its December and we add 3? I always use Dayjs for this, I don't even remember how the native one works ehehehe

2023-07-11 21:00 UTC, FedeMadoery approved these changes

2023-07-11 21:00 UTC, FedeMadoery commented on src/pagePartials/profile/myProfile/NearToExpireList.tsx
> +  // TODO now "NEAR TO EXPIRE" is in max 1 month, we will change this to configurable time
Add a config button, on the right side of the header, maybe a wear or something similar, where the user can choose btw "One month", "Two weeks" "One week"

I do this comment, so we can create a task from it :)

2023-07-11 21:00 UTC, FedeMadoery commented on src/pagePartials/profile/myProfile/PendingList.tsx
> +      async function handleClaimBadge(badgeId: string) {
Would be nice if we show a modal/popup that shows to the user how much money will be given back to him from the mint deposit.

I do this comment, so we can create a task from it :)

2023-07-12 07:43 UTC, Agupane requested changes

2023-07-12 07:43 UTC, Agupane commented on src/pagePartials/profile/Profile.tsx
> +      {filterType === 'badgesIAmReviewing' && <BadgesIAmReviewingSection />}
Would be possible to create an enum with the `filterTypes`? I guess it would scale better than hardcode this everytime

2023-07-12 07:43 UTC, Agupane commented on src/subgraph/queries/badge.ts
> +// export const BADGES_USER_IS_REVIEWING = gql`
is this on TODO or can be removed?

2023-07-12 13:35 UTC, ramabit commented on src/pagePartials/profile/myProfile/NearToExpireList.tsx
> +  // TODO now "NEAR TO EXPIRE" is in max 1 month, we will change this to configurable time
added #140

2023-07-12 13:38 UTC, ramabit commented on src/pagePartials/profile/myProfile/PendingList.tsx
> +      async function handleClaimBadge(badgeId: string) {
added #141

2023-07-12 22:04 UTC, FedeMadoery approved these changes

2023-07-13 07:55 UTC, merged