feat: Add protocol statistic
thebadge/thebadge-dapp pull request #162
Opened 2023-08-03 00:16 UTC by FedeMadoery

# Description

The component is ready but it had hardcoded values bc we need to merge the SG... When the SG is ready I will add a little improvements and will be ready

2023-08-03 07:37 UTC, Agupane reviewed
Ok that was fast, great work!
I deployed the new subgraph, you can go ahead with the connection

2023-08-03 17:57 UTC, ramabit requested changes

2023-08-03 17:57 UTC, ramabit commented on i18n/translations.en.json
> +      "owners": "BADGES\nOWNERS",
typo, should say: BADGE\nOWNERS or simply OWNERS
btw I would put it not all uppercase in this file, but modify that with css

2023-08-03 17:57 UTC, ramabit commented on i18n/translations.en.json
> +      "creators": "BADGES\nCREATORS",
typo, should say: BADGE\nCREATORS or simply CREATORS
btw I would put it not all uppercase in this file, but modify that with css

2023-08-03 17:57 UTC, ramabit commented on i18n/translations.en.json
> +      "curators": "BADGES CURATORS"
typo, should say: BADGE\nCURATORS or simply CURATORS
btw I would put it not all uppercase in this file, but modify that with css

2023-08-04 22:54 UTC, Agupane approved these changes

2023-08-07 16:46 UTC, ramabit approved these changes

2023-08-07 16:47 UTC, merged