feat: Add pulling for dispute id on profile
thebadge/thebadge-dapp pull request #181
Opened 2023-08-16 13:13 UTC by FedeMadoery

# Description

Add skeleton
Improve translations

2023-08-16 13:18 UTC, Agupane requested changes

2023-08-16 13:18 UTC, Agupane commented on i18n/translations.en.json
> +      "seeDisputeTooltip": "When you rice a challenge, a kleros dispute is created to resolve it and you can see how its going on the Kleros Court",
When you `raise` a challenge

2023-08-16 13:18 UTC, Agupane commented on i18n/translations.en.json
> +      "viewAll": "View more",
`View details`

2023-08-16 15:45 UTC, ramabit requested changes

2023-08-16 15:45 UTC, ramabit commented on src/components/helpers/FilteredList.tsx
> +      onSearch()
why the initial search does not use the default selected filters?

2023-08-16 15:45 UTC, ramabit commented on src/components/helpers/FilteredList.tsx
> +          Last update: <TimeAgo timestamp={lastSearchTimestamp} />
please add "Last update: " to the translations

2023-08-16 15:45 UTC, ramabit commented on src/utils/dateUtils.ts
> +    yy: '%d years',
should we add all this to translations?

2023-08-16 15:53 UTC, FedeMadoery commented on src/components/helpers/FilteredList.tsx
> +      onSearch()
It does, please read the `onSearch` declaration and feel free to ask about it on discord

2023-08-16 15:54 UTC, FedeMadoery commented on src/utils/dateUtils.ts
> +    yy: '%d years',
That is applied just for locale: `"en"` so it's fine, maybe on the near future we will need to customize the other relative time for each supported locale

2023-08-16 16:26 UTC, FedeMadoery commented on src/components/helpers/FilteredList.tsx
> +          Last update: <TimeAgo timestamp={lastSearchTimestamp} />
Good catch, done! Also added translation to the other words related to the list

2023-08-17 10:37 UTC, Agupane approved these changes
:rocket:

2023-08-17 11:26 UTC, ramabit approved these changes

2023-08-18 11:49 UTC, merged