feat: Create & Mint badge flow
thebadge/thebadge-dapp pull request #19
Opened 2023-02-09 17:23 UTC by FedeMadoery

Fix some issues
Improve label
Improve create badge forms
Improve from fields

# Description

Please include a summary of the changes and the link to the notion task. Please also include relevant motivation and context. List any dependencies that are required for this change.

## What's new?

- [ ] ....
- [ ] ....
- [ ] ....

## How this PR should be Tested?

Please describe the tests that you ran to verify your changes.

- [ ] Test A
- [ ] Test B

# Screenshots (if relevant)

2023-02-13 12:46 UTC, ramabit requested changes

2023-02-13 12:46 UTC, ramabit commented on pages/badge/[typeId]/[ownerAddress].tsx
> +                color: '#22DBBD',
please add color in theme and take it from there

2023-02-13 12:46 UTC, ramabit commented on pages/badge/[typeId]/[ownerAddress].tsx
> +              sx={{ color: '#22DBBD', fontSize: 10, fontWeight: 'bold' }}
please add color in theme and take it from there

2023-02-13 12:46 UTC, ramabit commented on pages/badge/[typeId]/[ownerAddress].tsx
> +              Minting your GitHub Passport is the first step to getting started with
please take text from translations

2023-02-13 12:46 UTC, ramabit commented on pages/badge/[typeId]/[ownerAddress].tsx
> +            <Typography variant="body2">Issued by: TheBadge</Typography>
please take text from translations

2023-02-13 12:46 UTC, ramabit commented on pages/badge/[typeId]/[ownerAddress].tsx
> +          <Typography>{badgeType?.badgesMintedAmount} # of claims</Typography>
please take text from translations

2023-02-13 12:46 UTC, ramabit commented on pages/badge/[typeId]/[ownerAddress].tsx
> +            <Typography>Check who else claimed it SEE ALL</Typography>
please take text from translations

2023-02-13 12:46 UTC, ramabit commented on pages/profile/[address].tsx
> +            : `This is the profile of ${addressOnUrl}`}
please take texts from translations

2023-02-13 12:46 UTC, ramabit commented on pages/profile/[address].tsx
> +                Minted badge {bt.id}
please take text from translations

2023-02-13 12:46 UTC, ramabit commented on pages/profile/[address].tsx
> +                Review DueDate: {dayjs.unix(bt.reviewDueDate).format('dddd, MMMM D, YYYY h:mm A')}
please take text from translations

2023-02-13 12:46 UTC, ramabit commented on pages/profile/[address].tsx
> +              <Typography>BadgeType Id: {bt.badgeType.id}</Typography>
please take text from translations

2023-02-13 12:46 UTC, ramabit commented on pages/profile/[address].tsx
> +              <Typography>BadgeType Minted Amount: {bt.badgeType.badgesMintedAmount}</Typography>
please take text from translations

2023-02-13 12:46 UTC, ramabit commented on pages/profile/index.tsx
> +          Please connect your wallet
please take text from translations

2023-02-13 12:46 UTC, ramabit commented on src/components/form/ExpirationField.tsx
> -  return dayjs().add(days, unit).format('DD/MM/YYYY')
I think we should have a general utils for date formatting

2023-02-13 12:46 UTC, ramabit commented on src/components/form/ImageInput.tsx
> +  backgroundColor: 'transparent',
take transparent color from theme

2023-02-13 12:46 UTC, ramabit commented on src/components/form/ImageInput.tsx
> +  borderColor: isDragging ? colors.green : 'white',
please use colors.white

2023-02-13 12:46 UTC, ramabit commented on src/components/form/ImageInput.tsx
> +                          Click here or drop
please take text from translations

2023-02-13 12:46 UTC, ramabit commented on src/components/form/SeveritySelector.tsx
> +      //  boxShadow: '0px 0px 0px 8px var(--box-shadow)',
why is this commented?

2023-02-13 12:46 UTC, ramabit commented on src/components/form/SeveritySelector.tsx
> +      //  boxShadow: '0px 0px 0px 14px var(--box-shadow)',
why is this commented?

2023-02-13 12:46 UTC, ramabit commented on src/components/form/SeveritySelector.tsx
> +      //  boxShadow: '0px 0px 0px 8px var(--box-shadow)',
why is this commented?

2023-02-13 12:46 UTC, ramabit commented on src/components/form/SeveritySelector.tsx
> +  //  label: Severity_Keys[1],
why is this code commented?

2023-02-13 12:46 UTC, ramabit commented on src/components/form/helpers/customSchemas.ts
> +    .min(25, { message: 'Text field most have at least 25 characters.' }),
please take text from translations

2023-02-13 12:46 UTC, ramabit commented on src/components/form/helpers/customSchemas.ts
> +    .min(2, 'The challenge time must be greater than 1 day'),
please take text from translations

2023-02-13 12:46 UTC, ramabit commented on src/components/form/helpers/customSchemas.ts
> +    'Description // Field description that explains what the field data is.',
please take text from translations

2023-02-13 12:46 UTC, ramabit commented on src/components/form/helpers/customSchemas.ts
>      .describe('Name // Field name that the user will be when they create the badge.'),
please take text from translations

2023-02-13 12:46 UTC, ramabit commented on src/components/form/helpers/customSchemas.ts
>    type: KlerosFieldTypeSchema.describe('Field Type // Type of the required data.'),
please take text from translations

2023-02-13 12:46 UTC, ramabit commented on src/components/form/klerosDynamicFormField/FormFieldCreator.tsx
> +            Name
please take text from translations

2023-02-13 12:46 UTC, ramabit commented on src/components/form/klerosDynamicFormField/FormFieldCreator.tsx
> +            Description
please take text from translations

2023-02-13 12:46 UTC, ramabit commented on src/components/form/klerosDynamicFormField/FormFieldCreator.tsx
> +            Type
please take text from translations

2023-02-13 12:46 UTC, ramabit commented on src/pagePartials/badge/mint/MintSteps.tsx
> +        <Button onClick={convertPreviewToImage}>Convert Preview to Image</Button>
please take text from translations

2023-02-13 12:46 UTC, ramabit commented on src/pagePartials/badge/mint/MintSteps.tsx
> +          <Typography>Total (Native token) need: {costs.totalMintCost}.</Typography>
please take text from translations

2023-02-13 12:46 UTC, ramabit commented on src/pagePartials/badge/mint/MintSteps.tsx
> +            <Tooltip title={'This will be returned if the evidence is valid'}>
please take text from translations

2023-02-13 12:46 UTC, ramabit commented on src/pagePartials/badge/type/CreateSteps.tsx
> +    'Description // This description will be showed on the Badge itself, you can use some helpers to inject user information on it.',
please take all texts in this file from translations

2023-02-13 12:47 UTC, ramabit requested changes

2023-02-13 12:47 UTC, ramabit commented on src/utils/kleros/generateKlerosListMetaEvidence.ts
>      description: `Add the evidence of the badge ${badgeName} to the list of evidences of ${badgeTypeName}.`,
please take all texts in this file from translations

2023-02-13 15:53 UTC, FedeMadoery commented on src/components/form/SeveritySelector.tsx
> +      //  boxShadow: '0px 0px 0px 8px var(--box-shadow)',
🧹

2023-02-13 15:53 UTC, FedeMadoery commented on src/components/form/SeveritySelector.tsx
> +      //  boxShadow: '0px 0px 0px 8px var(--box-shadow)',
🧹

2023-02-15 00:48 UTC, FedeMadoery commented
I move the most important stuff to the translation files and created tasks on the backlog for the other ones 👍

2023-02-16 21:50 UTC, merged