feat: Improve MetaEvidence and hooks related
thebadge/thebadge-dapp pull request #205
Opened 2023-08-26 15:04 UTC by FedeMadoery

# Description

Add sample page to add it as evidenceDisplay on Kleros Court

2023-08-28 13:18 UTC, ramabit requested changes

2023-08-28 13:18 UTC, ramabit commented on pages/evidence/index.tsx
> +    )
makes sense to refactor this in a function/util?

2023-08-28 13:18 UTC, ramabit commented on pages/evidence/index.tsx
> +        <TBDataView
this data view applies only for evidences? if so, I propose a name change to "EvidenceDataView" or similar

2023-08-28 13:18 UTC, ramabit commented on src/hooks/subgraph/useBadgeByDisputeId.tsx
> +  })
please remove logs here

2023-08-28 13:18 UTC, ramabit commented on src/hooks/subgraph/useBadgeModelKlerosMetadata.tsx
> +      console.log(badgeModelKlerosData)
please remove this logs

2023-08-28 13:18 UTC, ramabit commented on src/hooks/subgraph/useBadgeModelKlerosMetadata.tsx
> +      console.log(res)
please remove this logs

2023-08-28 13:18 UTC, ramabit commented on src/hooks/subgraph/useBadgeModelKlerosMetadata.tsx
> +      }
duplicated code, consider refactor here

2023-08-28 13:18 UTC, ramabit commented on src/hooks/subgraph/useBadgeModelKlerosMetadata.tsx
> +      }
duplicated code, consider refactor here

2023-08-28 16:07 UTC, FedeMadoery commented on pages/evidence/index.tsx
> +        <TBDataView
Good call, rename to `CourtEvidenceDataView`

2023-08-28 16:13 UTC, FedeMadoery commented on pages/evidence/index.tsx
> +    )
Not sure, it wont be used in any other place soo

2023-08-29 10:50 UTC, Agupane requested changes
Can you add the translation files?

2023-08-29 21:11 UTC, Agupane approved these changes

2023-08-29 21:16 UTC, ramabit approved these changes

2023-08-29 21:17 UTC, merged