feat: Creator statistics
thebadge/thebadge-dapp pull request #216
Opened 2023-09-01 10:57 UTC by FedeMadoery

# Description

Add base elements for user statistics, and implements the creator statistics

2023-09-02 07:38 UTC, Agupane requested changes

2023-09-02 07:38 UTC, Agupane commented on src/pagePartials/profile/statistics/creator/CreatorStatistics.tsx
> +  amount = 'Amount of badge types created ',
Amount of badge models created

2023-09-02 07:38 UTC, Agupane commented on src/pagePartials/profile/statistics/creator/CreatorStatistics.tsx
> +  minters = 'Amount of users that minted badges types',
Amount of users that minted badge models

2023-09-02 07:38 UTC, Agupane commented on src/pagePartials/profile/statistics/creator/CreatorStatistics.tsx
> +  minted = 'Amount of badges types minted',
Amount of badge models minted

2023-09-02 10:52 UTC, ramabit commented on src/pagePartials/profile/statistics/creator/CreatorStatistics.tsx
> +  minters = 'Amount of users that minted badges types',
well, in reality the user mints badges, not badge models. So, this should be: "Amount of users that minted badges with the created badge models" or similar

2023-09-02 10:53 UTC, Agupane commented on src/pagePartials/profile/statistics/creator/CreatorStatistics.tsx
> +  minters = 'Amount of users that minted badges types',
but that would be extremelly long and will break the UI 
<img width="516" alt="image" src="https://github.com/thebadge/thebadge-dapp/assets/21086218/015f2e9d-5a53-4137-a8d3-3700c725269c">

2023-09-02 10:54 UTC, ramabit commented on src/pagePartials/profile/statistics/creator/CreatorStatistics.tsx
> +  minted = 'Amount of badges types minted',
Similar as above, this should be: "Amount of badges minted using created badge models"

2023-09-02 10:57 UTC, ramabit commented on src/pagePartials/profile/statistics/creator/CreatorStatistics.tsx
> +  minters = 'Amount of users that minted badges types',
we can for example remove the "Amount of" and allow in the UI a second line if needed

2023-09-02 10:58 UTC, Agupane commented on src/pagePartials/profile/statistics/creator/CreatorStatistics.tsx
> +  minters = 'Amount of users that minted badges types',
Yeah that would be good, removing "Amount of"

2023-09-02 10:59 UTC, ramabit commented on src/pagePartials/profile/statistics/creator/CreatorStatistics.tsx
> +  minters = 'Amount of users that minted badges types',
another option is to keep it keep like: "Users that minted badge model" and a tooltip explaining the larger description

2023-09-06 06:33 UTC, Agupane approved these changes

2023-09-06 06:33 UTC, merged