fix: Statistics selection
thebadge/thebadge-dapp pull request #242
Opened 2023-10-17 23:32 UTC by FedeMadoery

# Description

2023-10-20 15:59 UTC, ramabit requested changes

2023-10-20 15:59 UTC, ramabit commented on src/hooks/nextjs/useStatisticsVisibility.tsx
> +      console.log('useEffect')
please remove logs

2023-10-20 15:59 UTC, ramabit commented on src/hooks/nextjs/useStatisticsVisibility.tsx
> +  console.log('stack', stack)
please remove logs

2023-10-20 20:45 UTC, FedeMadoery commented on src/hooks/nextjs/useStatisticsVisibility.tsx
> +  console.log('stack', stack)
Yeah, but i was waiting the confirmation about it is working for you guys too hehehe

2023-10-23 16:04 UTC, ramabit commented on src/hooks/nextjs/useStatisticsVisibility.tsx
> +  console.log('stack', stack)
from I what I tested, it worked good for me

2023-10-23 16:04 UTC, ramabit approved these changes

2023-10-23 20:18 UTC, merged