feat: Add error checks
thebadge/thebadge-dapp pull request #51
Opened 2023-04-05 23:08 UTC by FedeMadoery

# Description

On this PT we add three HOCs to prevent usage of the app functionalities without connecting the wallet or without being a creator or in the last case if you want to mint a badge that you already own.

2023-04-06 08:17 UTC, Agupane commented on src/components/assets/BadgeAnimatedLogo.tsx
> +    import('lottie-web').then((Lottie) => setLottie(Lottie.default))
👀

2023-04-06 08:17 UTC, Agupane commented on src/hooks/useIsCreator.tsx
> +export default function useIsCreator() {
💯

2023-04-06 08:19 UTC, ramabit commented on src/pagePartials/errors/displays/ConnectWalletError.tsx
> +  maxWidth: '850px',
we will need to touch this when mobile support

2023-04-06 08:22 UTC, Agupane requested changes

2023-04-06 08:22 UTC, Agupane commented on src/hooks/useIsCreator.tsx
> +export default function useIsCreator() {
a little picky but I think it may worth the effort: can we refactor this hook like this:

```
export default function useIsCreator(address: string) {}
```

In this way we can use it for every user even if the user that we want to do the validation is not connected and we the parameter via address for example (for example for looking the profile of an user)

2023-04-06 08:22 UTC, Agupane commented on src/pagePartials/errors/displays/AlreadyOwnThisBadgeError.tsx
> +        aria-label="close you already own this badge modal"
can this be translated?

2023-04-06 08:22 UTC, Agupane commented on src/pagePartials/errors/displays/AlreadyOwnThisBadgeError.tsx
> +            You already own this badge
same, translation

2023-04-06 08:22 UTC, Agupane commented on src/pagePartials/errors/displays/ConnectWalletError.tsx
> +          aria-label="close connect your wallet modal"
translation

2023-04-06 08:22 UTC, Agupane commented on src/pagePartials/errors/displays/ConnectWalletError.tsx
> +            Please, to continue it is necessary that you connect your wallet.
translations

2023-04-06 08:22 UTC, Agupane commented on src/pagePartials/errors/displays/NotACreatorError.tsx
> +          Please, to continue it is necessary that you have registered as a creator,{' '}
translations

2023-04-06 08:22 UTC, Agupane commented on src/pagePartials/errors/requiredConnection.tsx
> +          Switch to {chainsConfig[appChainId].name}
translation

2023-04-06 08:22 UTC, Agupane commented on src/pagePartials/errors/requiredConnection.tsx
> +  const isWrongNetwork = isConnected && walletChainId !== appChainId
can we move all this logic to a hook?

2023-04-06 08:33 UTC, Agupane requested changes

2023-04-06 11:07 UTC, FedeMadoery commented on src/pagePartials/errors/requiredConnection.tsx
> +  const isWrongNetwork = isConnected && walletChainId !== appChainId
No, for now at least, I do not want to allow another way to validate that, we already have the `requiredConnection.tsx` that should be used in those cases where is needed to validate the wallet and the network.

2023-04-06 11:11 UTC, FedeMadoery commented on src/pagePartials/errors/displays/ConnectWalletError.tsx
> +  maxWidth: '850px',
We are not going to support mobile in a short term, but.... Why? Any suggestions?

2023-04-07 10:58 UTC, Agupane approved these changes

2023-04-11 10:45 UTC, merged