feat: Badge Type explorer with info preview
thebadge/thebadge-dapp pull request #54
Opened 2023-04-19 21:21 UTC by FedeMadoery

# Description

WIP - I will add the description soon

2023-04-21 16:24 UTC, ramabit commented on pages/badge/explorer.tsx
> +                  BadgeType Info
please move text to translations file

2023-04-21 16:24 UTC, ramabit commented on pages/badge/explorer.tsx
> +          badgeTypes[selectedBadgeType] && (
perhaps this preview can be delegated to a function, so the code looks cleaner and easier to understand

2023-04-21 16:24 UTC, ramabit commented on pages/badge/explorer.tsx
> +                      // router.push(`/badge/mint/${bt.id}`)
no behavior on click? need a 'TODO' here?

2023-04-21 16:24 UTC, ramabit commented on src/components/helpers/FilteredList.tsx
> -  justifyContent: 'center',
how affects different viewports if we remove the centering?

2023-04-24 19:00 UTC, FedeMadoery commented on src/components/helpers/FilteredList.tsx
> -  justifyContent: 'center',
It has been moved to the usage, bc its changes based on the preview element

2023-04-27 14:45 UTC, ramabit requested changes

2023-04-27 14:45 UTC, ramabit commented on i18n/translations.en.json
> +        "createdBy": "Crated By"
Created By*

2023-04-30 21:19 UTC, merged