Feature/faqs
thebadge/thebadge-dapp pull request #63
Opened 2023-05-06 19:01 UTC by lolo-vignolo

# Description

FAQs section which is inside of the home screen. It is an accordion with titles and descriptions

## What's new?

It is only architecture with styles without states management

## How this PR should be Tested?

Please describe the tests that you ran to verify your changes.

- [ ] Test A
- [ ] Test B

# Screenshots (if relevant)

2023-05-08 10:47 UTC, FedeMadoery reviewed
Works as expected, awesome!

2023-05-08 10:47 UTC, FedeMadoery commented on src/pagePartials/home/FrequentQuestions.tsx
> +                {t(`home.FAQs.${data}.description`)}
I think it will be nice to have a `read more` at the end of each description, with a link to the docs

2023-05-08 15:06 UTC, ramabit commented on src/pagePartials/home/FrequentQuestions.tsx
> +                {t(`home.FAQs.${data}.description`)}
please keep also translation keys not capitalized

2023-05-09 20:13 UTC, ramabit requested changes
One small detail: see that when I open one faq, the divider line above disappears somehow
![Screenshot 2023-05-09 at 22 11 48](https://github.com/thebadge/thebadge-dapp/assets/5194886/c57fcdb9-46e5-4ffe-b884-e3cb475487d4)

2023-05-10 00:20 UTC, lolo-vignolo commented
Perfect Fer, now It is fixed. If you see something to improve, do not hesitate to let me know.

2023-05-10 11:30 UTC, ramabit approved these changes

2023-05-10 18:30 UTC, FedeMadoery approved these changes
Nice work man! Congrats on your first PR! I left a small comment, but I approve it anyways since it's quite simple.

2023-05-10 18:30 UTC, FedeMadoery commented on src/pagePartials/home/FrequentQuestions.tsx
> +                  target="_blank"
Would be nice to add an underline here, to know that there is a like there at first glance.

`style={{ textDecoration: 'underline' }}`

2023-05-11 21:51 UTC, merged