feat: Refactor Badge Model creation
thebadge/thebadge-dapp pull request #99
Opened 2023-05-15 20:25 UTC by FedeMadoery

# Description

WIP 🚧

2023-05-18 12:36 UTC, nicosampler commented on pages/badge/mint/[typeId].tsx
> +            klerosCost: formatUnits(0, 18), // TODO fix this by checking the deposit cost. It has to be a dynamic call to klerosController
can we address this? here is the method we should call to get the missing information https://github.com/thebadge/thebadge-contracts/blob/main/src/badgeTypeControllers/kleros.sol#L191

2023-05-18 12:40 UTC, nicosampler commented on src/hooks/subgraph/useBadgeType.tsx
> +      badgeModelMetadata,
here we are mixing the metadata, badgeMetadata has information internal to TheBadge while registrationUri is the criteria, which one do we need? can we name the variable properly to avoid confusion?

2023-05-18 12:40 UTC, nicosampler commented on src/pagePartials/badge/curate/CurationCriteriaLink.tsx
> +  const badgeTypeData = useBadgeModel(badgeTypeId)
badgeModelData

2023-05-18 12:41 UTC, nicosampler commented on src/pagePartials/badge/curate/challenge/ChallengeCost.tsx
> +  const badgeTypeData = useBadgeModel(badgeTypeId)
same here

2023-05-18 12:46 UTC, nicosampler commented on src/pagePartials/badge/curate/useBadgeCost.ts
>  export function useBadgeCost(badgeId: BigNumberish, wallet: string) {
this hook and getMintvalue can be confusing, perhaps we should be more specific about the names

useBadgeMintValue: this one should include everything deposit + creatorFee
creatorFee: when needed to be obtained independently it should be obtained by consulting badgeModel query

2023-05-18 12:48 UTC, nicosampler commented on src/pagePartials/badge/explorer/ListingCriteriaPreview.tsx
> +  const badgeTypeData = useBadgeModel(badgeTypeId)
Model

2023-05-18 12:50 UTC, nicosampler commented on src/pagePartials/badge/model/stateMachine/machine/createModelMachine.ts
> +              target: '#Badge Model Creation.Badge Strategy.idle',
can we use names without space? camelCase could be a better alternative I believe.

2023-07-04 10:53 UTC, Agupane requested changes

2023-07-04 10:53 UTC, Agupane commented on src/components/form/ExpirationField.tsx
> +                    `\n e.g. If you mint this badge today, It will expire on: ${validTo(value)}`
this should use translation

2023-07-04 10:53 UTC, Agupane commented on src/components/form/SeveritySelector/AdvanceView.tsx
> +const numberOfJurorExplanations =
Its possible to have this with translation? (the translation is not necessary but the configuration in place)

2023-07-04 10:53 UTC, Agupane commented on src/components/form/SeveritySelector/index.tsx
> +  const [auxValue, setAuxValue] = useState<number>(1)
what is this exactly? can be renamed to something more descriptive?

2023-07-04 10:53 UTC, Agupane commented on src/components/form/SeveritySelector/styled.tsx
> +    borderBottom: 'none !important',
are all the !importants really needed? there is no way to avoid using it?

2023-07-04 10:53 UTC, Agupane commented on src/components/form/SeveritySelector/utilts.ts
> +    amountOfJurors: +(process.env.NEXT_PUBLIC_BADGE_MODEL_SEVERITY_NORMAL_JURORS || 0),
the `process.env` should be moved to `common.ts` file, maybe we can just have there a config object with all the severity levels

2023-07-04 10:53 UTC, Agupane commented on src/components/form/TokenInput.tsx
> +export default function TokenInputWithTSForm({
This should be another file right?

2023-07-04 11:17 UTC, Agupane requested changes

2023-07-04 11:17 UTC, Agupane commented on pages/badge/model/create.tsx
> +          process.env.NEXT_PUBLIC_KLEROS_DEFAULT_COURT as string,
this also should be moved to either `common.ts` or `config.ts`

2023-07-04 11:17 UTC, Agupane commented on src/pagePartials/badge/model/steps/preview/BadgeModelConfirmation.tsx
> +          By continuing, you agree to our{' '}
translations

2023-07-04 11:17 UTC, Agupane commented on src/pagePartials/badge/model/steps/preview/BadgeModelConfirmation.tsx
> +          fontSize={'14px !important'}
is the !important non-avoidable?

2023-07-04 11:17 UTC, Agupane commented on src/pagePartials/badge/model/steps/strategy/BadgeModelStrategy.tsx
> +            label={'Challenge period duration'}
Translations

2023-07-04 11:17 UTC, Agupane commented on src/pagePartials/badge/model/steps/strategy/PDFRequirementInput.tsx
> +          <Typography variant="dAppBody4">Download Template</Typography>
Translations

2023-07-04 11:17 UTC, Agupane commented on src/pagePartials/badge/model/steps/strategy/RequirementInput.tsx
> +        Create the acceptance criteria
translations

2023-07-04 11:17 UTC, Agupane commented on src/pagePartials/badge/model/utils.ts
> +  const ONE_DAY = 24 * 60 * 60 * 1000 /* ms */
this should be moved to `common.ts`

2023-07-04 11:17 UTC, Agupane commented on src/pagePartials/badge/model/utils.ts
> +export function getCriteriaTemplate() {
translations possible?

2023-07-04 13:06 UTC, FedeMadoery commented on src/components/form/TokenInput.tsx
> +export default function TokenInputWithTSForm({
No, I mean it could be but it would add too much noise for my taste and it doesn't worth it, also It is going to add the need for a refactor in the already implemented code that uses that one, that is also the main reason becaouse I did an `export default` for this

2023-07-04 13:16 UTC, FedeMadoery commented on src/pagePartials/badge/model/utils.ts
> +export function getCriteriaTemplate() {
It's not easy, but it can be done. Also, it will need some work to "refresh" the form, bc the user can change the language during the form competition and this criteria template is used as the default value, so with that said we will need to re-start the form, its not like the rendered text that is automatically done.

2023-07-04 13:29 UTC, FedeMadoery commented on src/pagePartials/badge/model/utils.ts
> +export function getCriteriaTemplate() {
I'm going to create a new issue for this, since it would take too much time for me to do it now

2023-07-06 13:15 UTC, Agupane requested changes

2023-07-06 13:15 UTC, Agupane commented on src/pagePartials/badge/model/steps/strategy/RequirementInput.tsx
> +                  placeholder={'Write your acceptance criteria'}
Missing translation

2023-07-06 13:15 UTC, Agupane commented on src/pagePartials/badge/model/steps/strategy/RequirementInput.tsx
> +              Upload criteria as <span style={{ textDecoration: 'underline' }}>PDF</span>.
Missing translation

2023-07-06 13:15 UTC, Agupane commented on src/components/form/SeveritySelector/AdvanceView.tsx
> +const numberOfJurorExplanations =
reminder

2023-07-06 13:15 UTC, Agupane commented on i18n/translations.en.json
>              "subTitle": "This is how your badge is going to look like when a user obtain it."
typo fix to:
"This is how your badge is going to look when a user obtains it."

2023-07-06 17:31 UTC, FedeMadoery commented on src/pagePartials/badge/model/steps/strategy/RequirementInput.tsx
> +              Upload criteria as <span style={{ textDecoration: 'underline' }}>PDF</span>.
This will be removed when we remove the PDF option.

2023-07-07 14:07 UTC, merged